### ISSUE TITLE
error in check_inputs_design(): Modfed and dopt not included

### ISSUE THREAD

**Issue by marilotte** [jhelvy/cbcTools#35]
The code right now is:

    # Check on restricted profile sets

    if (profiles_restricted) {
      if (!method %in% c('random', 'full')) {
        stop(
          'Restricted profile sets can only be used with the "random", "full" ',
          '"dopt", or "Modfed" methods'
        )
      }
    }

Because of this it's not possible to use a restricted profile with either Modfed or dopt methods. This sould be an easy fix, however :)

Cheers!
Marianne

**Comment by jhelvy** [comment]
This was already fixed [here](https://github.com/jhelvy/cbcTools/blob/main/R/input_checks.R#L116-L125), but I don't believe the fix is available on CRAN yet. You can install from Github to get the latest.
